// Auto-generated by GitHub Actions — do not edit manually
window.GAMES_DATA = [
  {
    "title": "Ancestors: The Humankind Odyssey",
    "studio": "Panache Jeux Numériques",
    "genre": "Adventure",
    "desc": "A third-person open world survival game spanning 10 million years of human evolution.",
    "emoji": "🦴",
    "color_from": "#0a1408",
    "color_to": "#0d1e0a"
  },
  {
    "title": "Assassin's Creed Syndicate",
    "studio": "Ubisoft Québec",
    "genre": "Action",
    "desc": "Take back Victorian London as twins Jacob and Evie Frye, building a criminal empire to fight the Templar stranglehold on the city.",
    "emoji": "🗡️",
    "color_from": "#14100a",
    "color_to": "#20180a"
  },
  {
    "title": "Batman: Arkham Origins",
    "studio": "WB Games Montréal",
    "genre": "Action",
    "desc": "Set years before Arkham Asylum, this prequel follows a young Batman facing assassins on a bounty — including his first encounter with the Joker.",
    "emoji": "🦇",
    "color_from": "#0a0a14",
    "color_to": "#14141e"
  },
  {
    "title": "Bloodroots",
    "studio": "Paper Cult",
    "genre": "Action",
    "desc": "An ultraviolent action game where every object in the world is a weapon. A bloody ballet of improvisation and instinct.",
    "emoji": "🪓",
    "color_from": "#1a0808",
    "color_to": "#250a0a"
  },
  {
    "title": "Castle Story",
    "studio": "Sauropod Studio",
    "genre": "Strategy",
    "desc": "A creative voxel-based strategy game where you build castles one brick at a time and defend them from monsters.",
    "emoji": "🧱",
    "color_from": "#0a0e14",
    "color_to": "#0d1420"
  },
  {
    "title": "Dead by Daylight",
    "studio": "Behaviour Interactive",
    "genre": "Horror",
    "desc": "Asymmetrical multiplayer horror where one Killer hunts four Survivors. A global phenomenon with tens of millions of players.",
    "emoji": "🩸",
    "color_from": "#200a0a",
    "color_to": "#3d0d0d"
  },
  {
    "title": "Deceive Inc.",
    "studio": "Sweet Bandits Studios",
    "genre": "Action",
    "desc": "Go undercover as a world-class spy in this tense multiplayer game of subterfuge. Disguise, deceive, and eliminate.",
    "emoji": "🕵️",
    "color_from": "#10080a",
    "color_to": "#1a0d10"
  },
  {
    "title": "Deus Ex GO",
    "studio": "Square Enix Montréal",
    "genre": "Puzzle",
    "desc": "A turn-based puzzle infiltration game set in a stylised Deus Ex universe, placing Agent Jensen in covert missions solved through strategy.",
    "emoji": "🤖",
    "color_from": "#100e08",
    "color_to": "#201a08"
  },
  {
    "title": "Deus Ex: Human Revolution",
    "studio": "Eidos-Montréal",
    "genre": "RPG",
    "desc": "A groundbreaking action-RPG set in cyberpunk 2027, where augmented security expert Adam Jensen investigates a conspiracy that could change humanity forever.",
    "emoji": "🦾",
    "color_from": "#1a1408",
    "color_to": "#2a2010"
  },
  {
    "title": "Deus Ex: Mankind Divided",
    "studio": "Eidos-Montréal",
    "genre": "RPG",
    "desc": "Two years after Human Revolution, Adam Jensen navigates a world of augmentation apartheid to uncover a deeper, world-threatening conspiracy.",
    "emoji": "🦿",
    "color_from": "#141008",
    "color_to": "#201808"
  },
  {
    "title": "Epic Manager",
    "studio": "ManaVoid Entertainment",
    "genre": "Strategy",
    "desc": "A unique mashup of sports management simulation and classic JRPGs — recruit heroes, build a team, and compete in adventurers' leagues.",
    "emoji": "🏆",
    "color_from": "#0c1008",
    "color_to": "#141a0a"
  },
  {
    "title": "Far Cry 4",
    "studio": "Ubisoft Montréal",
    "genre": "Action",
    "desc": "Stranded in the fictional Himalayan kingdom of Kyrat, you must navigate a civil war and the eccentric cruelty of self-appointed king Pagan Min.",
    "emoji": "🏔️",
    "color_from": "#0d1a0a",
    "color_to": "#1a2810"
  },
  {
    "title": "Foundation",
    "studio": "Polymorph Games",
    "genre": "Strategy",
    "desc": "A grid-less sprawling medieval city builder with organic development and monument construction.",
    "emoji": "🏰",
    "color_from": "#14100a",
    "color_to": "#1e1808"
  },
  {
    "title": "Hellpoint",
    "studio": "Cradle Games",
    "genre": "Action",
    "desc": "A dark multiplayer action RPG set in the aftermath of a quantum cataclysm aboard a space station orbiting a black hole, filled with occult horrors.",
    "emoji": "⚫",
    "color_from": "#0a0810",
    "color_to": "#16081e"
  },
  {
    "title": "Hitman GO",
    "studio": "Square Enix Montréal",
    "genre": "Puzzle",
    "desc": "A turn-based puzzle game where Agent 47 navigates elegant diorama-style set pieces on a grid — strategy and precision over brute force.",
    "emoji": "🎯",
    "color_from": "#100a0a",
    "color_to": "#1e1010"
  },
  {
    "title": "Hitman: Sniper",
    "studio": "Square Enix Montréal",
    "genre": "Action",
    "desc": "Take on contracts as Agent 47 armed only with a sniper rifle, using creativity and precision from a fixed vantage point to eliminate targets.",
    "emoji": "🔭",
    "color_from": "#0a0c10",
    "color_to": "#10121a"
  },
  {
    "title": "Jotun: Valhalla Edition",
    "studio": "Thunder Lotus",
    "genre": "Action",
    "desc": "Hand-drawn action-exploration set in Norse mythology. Play Thora, a Viking warrior who must prove herself to the gods.",
    "emoji": "⚡",
    "color_from": "#0a0810",
    "color_to": "#100a18"
  },
  {
    "title": "Knight Squad 2",
    "studio": "Chainsawesome Games",
    "genre": "Co-op",
    "desc": "An 8-player arcade multiplayer mixing Bomberman with Gauntlet across 13 chaotic game modes.",
    "emoji": "⚔️",
    "color_from": "#10080e",
    "color_to": "#18091a"
  },
  {
    "title": "Lara Croft GO",
    "studio": "Square Enix Montréal",
    "genre": "Puzzle",
    "desc": "A turn-based puzzle-adventure set in a long-forgotten world. Navigate treacherous labyrinths and solve ancient mysteries as Lara Croft.",
    "emoji": "🏺",
    "color_from": "#0a0e10",
    "color_to": "#10181a"
  },
  {
    "title": "Legends of Ethernal",
    "studio": "Lucid Dreams Studio",
    "genre": "Adventure",
    "desc": "A 2D action-adventure with hand-crafted environments, clever puzzles, and a rich world to explore as you search for your missing parents.",
    "emoji": "🌿",
    "color_from": "#0a0e18",
    "color_to": "#0d1428"
  },
  {
    "title": "Outlast",
    "studio": "Red Barrels",
    "genre": "Horror",
    "desc": "A true survival horror experience set in a remote psychiatric hospital, where your only option is to run and hide.",
    "emoji": "📷",
    "color_from": "#160a0a",
    "color_to": "#200d0d"
  },
  {
    "title": "Outward",
    "studio": "Nine Dots Studio",
    "genre": "RPG",
    "desc": "An open-world RPG with punishing survival elements — cold nights, harsh weather, and a world that doesn't care if you live.",
    "emoji": "⚔️",
    "color_from": "#0a0e14",
    "color_to": "#0d121e"
  },
  {
    "title": "Prison Boss VR",
    "studio": "Ultimerse",
    "genre": "Adventure",
    "desc": "A VR crafting and trading game where your play space becomes a jail cell. Craft contraband, build a reputation, and don't get caught by the guards.",
    "emoji": "🔒",
    "color_from": "#0c0c0c",
    "color_to": "#181818"
  },
  {
    "title": "Rise of Madness",
    "studio": "Hibernum Créations",
    "genre": "Strategy",
    "desc": "A zombie survival game set in 1840 Montréal. Manage a desperate community, build shelter, scavenge resources, and search for a cure.",
    "emoji": "🧟",
    "color_from": "#120808",
    "color_to": "#1e0c0c"
  },
  {
    "title": "Sea of Stars",
    "studio": "Sabotage Studio",
    "genre": "RPG",
    "desc": "A BAFTA-winning turn-based RPG inspired by 90s classics, blending stunning pixel art with tactical combat.",
    "emoji": "🌊",
    "color_from": "#0a0d20",
    "color_to": "#0d1a2e"
  },
  {
    "title": "SEASON: A Letter to the Future",
    "studio": "Scavengers Studio",
    "genre": "Adventure",
    "desc": "A young woman leaves her secluded village to document a world on the cusp of an apocalypse.",
    "emoji": "🍂",
    "color_from": "#0a100e",
    "color_to": "#0d1814"
  },
  {
    "title": "Ship of Fools",
    "studio": "Fika Productions",
    "genre": "Roguelike",
    "desc": "A cooperative roguelite set in a marine universe. Two Fools aboard a ship, braving the Everlasting Storm.",
    "emoji": "🚢",
    "color_from": "#080d1a",
    "color_to": "#0a1225"
  },
  {
    "title": "Spiritfarer",
    "studio": "Thunder Lotus",
    "genre": "Adventure",
    "desc": "A cozy management game about dying. Build a boat, explore the world, and help spirits pass on in this emotional masterpiece.",
    "emoji": "⛵",
    "color_from": "#0a1a14",
    "color_to": "#0d2010"
  },
  {
    "title": "Stories: The Path of Destinies",
    "studio": "Spearhead Games",
    "genre": "RPG",
    "desc": "An action-RPG in a fairytale world of rebels and sky-pirates where every choice branches the story — play all paths to uncover the true ending.",
    "emoji": "📖",
    "color_from": "#0e080a",
    "color_to": "#18100c"
  },
  {
    "title": "Subaeria",
    "studio": "iLLOGIKA",
    "genre": "Roguelike",
    "desc": "An intense action puzzler with roguelike elements. Use your wits to manipulate enemies into destroying each other.",
    "emoji": "🎯",
    "color_from": "#080a16",
    "color_to": "#0a0d20"
  },
  {
    "title": "The Messenger",
    "studio": "Sabotage Studio",
    "genre": "Action",
    "desc": "A side-scrolling action platformer about a ninja carrying a scroll through a cursed world, shifting between 8-bit and 16-bit eras.",
    "emoji": "🥷",
    "color_from": "#0a0a20",
    "color_to": "#10081a"
  },
  {
    "title": "Therian Saga",
    "studio": "Virtys",
    "genre": "RPG",
    "desc": "A rich browser-based MMORPG that stands apart from the crowd, offering deep crafting systems, trade networks, and a living world to explore.",
    "emoji": "🐺",
    "color_from": "#080e14",
    "color_to": "#0c1420"
  },
  {
    "title": "Ultimate Chicken Horse",
    "studio": "Clever Endeavour",
    "genre": "Co-op",
    "desc": "A party platformer where you build the level as you play, placing traps to stop your friends.",
    "emoji": "🐔",
    "color_from": "#0a1a0a",
    "color_to": "#0d200d"
  },
  {
    "title": "We Happy Few",
    "studio": "Compulsion Games",
    "genre": "Action",
    "desc": "Survival action set in a drug-fuelled, darkly comic alternate 1960s England where conformity is enforced at all costs.",
    "emoji": "😊",
    "color_from": "#1a150a",
    "color_to": "#28200a"
  },
  {
    "title": "Zombiotik",
    "studio": "Studio Shrub",
    "genre": "Co-op",
    "desc": "A chaotic 3D local multiplayer game for up to 8 players based on zombie tag — the last human standing wins.",
    "emoji": "🧠",
    "color_from": "#0c0e08",
    "color_to": "#181e0c"
  }
];
window.STUDIOS_DATA = [
  {
    "name": "Behaviour Interactive",
    "city": "Montréal",
    "desc": "One of Canada's largest independent studios, creator of the landmark asymmetrical horror franchise Dead by Daylight — a cultural phenomenon with tens of millions of players worldwide.",
    "website": "https://www.bhvr.com",
    "games": [
      "Dead by Daylight",
      "Meet Your Maker"
    ]
  },
  {
    "name": "Clever Endeavour Games",
    "city": "Montréal",
    "desc": "A small, passionate studio behind Ultimate Chicken Horse — a party game phenomenon beloved for its chaotic creativity and its thriving competitive community.",
    "website": "https://www.cleverendeavour.com",
    "games": [
      "Ultimate Chicken Horse"
    ]
  },
  {
    "name": "Compulsion Games",
    "city": "Montréal",
    "desc": "A creative indie studio known for atmospheric, narrative-driven games. We Happy Few's darkly comic alternate-history world earned global critical acclaim.",
    "website": "https://compulsiongames.com",
    "games": [
      "We Happy Few",
      "Contrast"
    ]
  },
  {
    "name": "Eidos-Montréal",
    "city": "Montréal",
    "desc": "A global AAA powerhouse behind the Deus Ex and Tomb Raider legacy, and Marvel's Guardians of the Galaxy — a franchise-defining critical darling.",
    "website": "https://eidosmontreal.com",
    "games": [
      "Deus Ex: Mankind Divided",
      "Shadow of the Tomb Raider"
    ]
  },
  {
    "name": "Gameloft",
    "city": "Montréal",
    "desc": "A global mobile gaming leader with a Montréal hub producing high-quality titles across racing, action, and adventure genres played by hundreds of millions.",
    "website": "https://www.gameloft.com",
    "games": [
      "Asphalt 9",
      "Modern Combat 5",
      "Disney Magic Kingdoms"
    ]
  },
  {
    "name": "Nine Dots Studio",
    "city": "Montréal",
    "desc": "An independent studio dedicated to deep, challenging open-world RPGs that respect the player's intelligence and reward exploration and perseverance.",
    "website": "https://ninedotsstudio.com",
    "games": [
      "Outward",
      "Outward: Definitive Edition"
    ]
  },
  {
    "name": "Panache Digital Games",
    "city": "Montréal",
    "desc": "Founded by the creator of Assassin's Creed, Panache explores uncharted territory with games rooted in humanity's deep history and survival instincts.",
    "website": "https://panachedigital.com",
    "games": [
      "Ancestors: The Humankind Odyssey"
    ]
  },
  {
    "name": "Red Barrels",
    "city": "Montréal",
    "desc": "A veteran-founded indie studio specializing in survival horror. The Outlast series set a new bar for first-person horror and has sold millions of copies worldwide.",
    "website": "https://www.redbarrelsgames.com",
    "games": [
      "Outlast",
      "Outlast 2",
      "The Outlast Trials"
    ]
  },
  {
    "name": "Sabotage Studio",
    "city": "Québec City",
    "desc": "Award-winning boutique studio crafting games with the soul of 90s classics. Sea of Stars won the BAFTA for Best Game and became one of the most celebrated indie RPGs in years.",
    "website": "https://www.sabotagestudio.com",
    "games": [
      "Sea of Stars",
      "The Messenger"
    ]
  },
  {
    "name": "Scavengers Studio",
    "city": "Montréal",
    "desc": "A thoughtful independent studio whose meditative game SEASON: A Letter to the Future earned universal praise for its unique approach to storytelling and world-building.",
    "website": "https://scavengersstudio.com",
    "games": [
      "SEASON: A Letter to the Future"
    ]
  },
  {
    "name": "Square Enix Montréal",
    "city": "Montréal",
    "desc": "A mobile and puzzle-focused studio renowned for reimagining AAA franchises as elegant, turn-based puzzle experiences that earned global awards.",
    "website": "https://www.se-montreal.com",
    "games": [
      "Hitman GO",
      "Lara Croft GO",
      "Deus Ex GO"
    ]
  },
  {
    "name": "Thunder Lotus Games",
    "city": "Montréal",
    "desc": "Hand-crafted games with deeply emotional narratives. Spiritfarer reframed how games can handle grief, reaching millions with its heartfelt management mechanics.",
    "website": "https://thunderlotusgames.com",
    "games": [
      "Spiritfarer",
      "Jotun",
      "Sundered"
    ]
  },
  {
    "name": "Ubisoft Montréal",
    "city": "Montréal",
    "desc": "One of the world's largest game studios and the creative engine behind Assassin's Creed, Far Cry, and Watch Dogs. A cornerstone of Québec's game industry since 1997.",
    "website": "https://montreal.ubisoft.com",
    "games": [
      "Assassin's Creed",
      "Far Cry 4",
      "Watch Dogs"
    ]
  },
  {
    "name": "Ubisoft Québec",
    "city": "Québec City",
    "desc": "The studio behind Assassin's Creed Syndicate and Odyssey — known for pushing the boundaries of open-world storytelling in the iconic franchise.",
    "website": "https://quebec.ubisoft.com",
    "games": [
      "Assassin's Creed Syndicate",
      "Assassin's Creed Odyssey"
    ]
  },
  {
    "name": "WB Games Montréal",
    "city": "Montréal",
    "desc": "Creator of Batman: Arkham Origins and Gotham Knights — a studio with deep expertise in building open-world action games set in beloved DC universes.",
    "website": "https://wbgamesmontreal.com",
    "games": [
      "Batman: Arkham Origins",
      "Gotham Knights"
    ]
  }
];
